// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfMlemWBBD2Zxr9X69ZJb9toGZYyJ-vGQ',
    appId: '1:427641136739:web:bbfa85b8927d1227413a56',
    messagingSenderId: '427641136739',
    projectId: 'lista-de-tarefas-5ab58',
    authDomain: 'lista-de-tarefas-5ab58.firebaseapp.com',
    storageBucket: 'lista-de-tarefas-5ab58.appspot.com',
    measurementId: 'G-GYK4B6WS2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyDwm3Y8iATXUSWab4tv0tfNGVQ0-wj0',
    appId: '1:427641136739:android:5ec2db16cd9059bd413a56',
    messagingSenderId: '427641136739',
    projectId: 'lista-de-tarefas-5ab58',
    storageBucket: 'lista-de-tarefas-5ab58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6PnSdQkjfNwpyOm15PSjGpGRX1hMELs4',
    appId: '1:427641136739:ios:0bc24c8bd2b09758413a56',
    messagingSenderId: '427641136739',
    projectId: 'lista-de-tarefas-5ab58',
    storageBucket: 'lista-de-tarefas-5ab58.appspot.com',
    iosBundleId: 'com.example.listaDeTarefas',
  );
}
